audiolibrary/urls.py
import os
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.views.static import serve
from django.views.generic import TemplateView


urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),  # Keep
    re_path(r'^oauth/', include('social_django.urls', namespace='social')),

    # application
    path('speakers/', include('speakers.urls')),
    path('amplifiers/', include('amplifiers.urls')),
    path('genre/', include('genre.urls')),
    path('library/', include('library.urls')),
    path('forum', include('forum.urls')),
    path('membership', include('membership.urls')),

]

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    re_path(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

forum/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

app_name = 'forum'

urlpatterns = [
    path('', TemplateView.as_view(template_name='forum/main.html'), name='all'),
]

home/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

app_name = 'home'

urlpatterns = [
    path('', TemplateView.as_view(template_name='home/main.html'), name='main'),
    path('register', views.register_request, name="register"),
    path('user', views.userpage, name="userprofile"),
]

library/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

app_name = 'library'

urlpatterns = [
    path('', TemplateView.as_view(template_name='library/main.html'), name='all'),
]

membership/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name = 'membership'

urlpatterns = [
    path('/<int:pk>', views.MemberDetailView.as_view(), name='member_detail'),
    ]

home/models.py
from django.db import models

# Create your models here.

home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from membership.models import UserDetail


class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

class UserDetailForm(forms.ModelForm):
    class Meta:
        model = UserDetail
        fields = ('speakers',)

home/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.conf import settings
from .forms import NewUserForm, UserForm, UserDetailForm
from django.contrib.auth import login
from django.contrib import messages
# Create your views here.


def register_request(request, backend='django.contrib.auth.backends.ModelBackend'):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            messages.success(request, "Registration successful")
            return redirect("home:main")
        messages.error(request, "Unsuccessful registration, Invalid information.")
    form = NewUserForm()
    return render(request=request, template_name="registration/register.html", context={"register_form":form})

def userpage(request):
    user_form = UserForm(instance=request.user)
    profile_form = UserDetailForm(instance=request.user.userdetail)
    return render(request=request, template_name="registration/profile.html",context={"user":request.user, "user_form":user_form, "profile_form":profile_form })

home/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>AwwBlog{% block title %}{% endblock title %}</title>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <!-- static file -->
    <link href=" /css/style.css" rel="stylesheet">
    <script src="/js/main.js"></script>

    <!-- highlight js -->
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/styles/monokai-sublime.min.css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>

</head>
<body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container">
      <a class="navbar-brand" href="/">AwwBlog</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">



        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link {% if request.path == '/tag/linux/' %}active{% endif %}" aria-current="page" href="{{ request.scheme }}://{{ request.get_host }}/tag/linux/">Linux</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if request.path == '/tag/tips/' %}active{% endif %}" href="{{ request.scheme }}://{{ request.get_host }}/tag/tips/">Tips</a>
          </li>

         <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Tutorial
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li>
              <a class="dropdown-item {% if request.path == '/tag/python/' %}active{% endif %}" href="{{ request.scheme }}://{{ request.get_host }}/tag/python/">Python</a>
            </li>

            <li>
              <a class="dropdown-item {% if request.path == '/tag/django/' %}active{% endif %}" href="{{ request.scheme }}://{{ request.get_host }}/tag/django/">Django</a>
            </li>

          </ul>
        </li>

        </ul>
        <form class="d-flex" action="/">
          <input class="form-control mr-0" type="search" value="{{request.GET.q}}" name="q" placeholder="Search" aria-label="Search">
        </form>
      </div>
    </div>
  </nav>

    <main class="container my-3">

        <h2 class="my-3">
          {% if request.GET.q is not null %}
            Search Results for "{{ request.GET.q }}"
          {% endif %}
        </h2>

        {% block content %}

        {% endblock content %}
    </main>
  <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

</body>
</html>

home/templates/base_bootstrap.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<!-- Edit dj4e-samples/settings.py and add APP_NAME = 'DJ4E Samples' or similar -->
<title>{% block title %}{{ settings.APP_NAME }}{% endblock %}</title>

<!-- Replace this value (42-42) with the one provided by the autograder -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" >
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" ></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>



<link rel="stylesheet" href="{% static 'css/style.css' %}">

<!-- javascript add -->
<script src="{% static 'js/main.js' %}"></script>
{% block head %} {% endblock %}

</head>
<body>
<div class="container">
{% block navbar %} {% endblock %}
{% block welcome %} {% endblock %}
{% block messages %}
    {% if messages %}
    {% for msg in messages %}
        <div class="alert alert-{{msg.level_tag}}" role="alert">
        {{msg.message}}
        </div>
    {% endfor %}
    {% endif %}
{% endblock %}
{% block content %}
{% endblock %}
</div>
{% block footer %} {% endblock %}
</body>
</html>

home/templates/base_menu.html
{% extends 'base_bootstrap.html' %}
{% load app_tags %} <!-- see home/templatetags/app_tags.py and dj4e-samples/settings.py -->
{% block navbar %}
<!-- https://www.w3schools.com/bootstrap/bootstrap_navbar.asp -->
<nav id="header-nav" class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
        <a  href="{% url 'home:main' %}">
            <div id="logo-img" alt="Logo image">

            </div>
        </a>
    </div>
    <!-- https://stackoverflow.com/questions/22047251/django-dynamically-get-view-url-and-check-if-its-the-current-page -->


  </div>
</nav>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <ul class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown link
          </a>
        <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'login' %}?next={% url 'home:main' %}">Action</a></li>
          <li><a class="dropdown-item" href="{% url 'login' %}?next={% url 'home:main' %}">Another action</a></li>
          <li><div class="dropdown-divider"></div></li>
          <li><a class="dropdown-item" href="#">Something else here</a></li>
        </ul>
      </li>
    </ul>

    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
<!-- <nav id="menu-nav" class="navbar navbar-default navbar-inverse">
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
<div class="collapse navbar-collapse" id="navbarSupportedContent">
<ul class="navbar-nav mr-auto">


            <li class="nav-item">
          <a href="{% url 'library:all' %}">ARLibrary</a>
            </li>

            <li class="nav-item">
          <a href="{% url 'forum:all' %}">Forum</a>
            </li>
</ul>
<ul  class="nav navbar-nav navbar-right">
      {% if not request.user.is_authenticated %}

          <li class="nav-item dropdown">
             <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Menu</a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
         <a href="{% url 'login' %}?next={% url 'home:main' %}">Login</a>
                  <a href="{% url 'home:register' %}?next={% url 'home:main' %}">Sign up</a>
        </div>
          </li>
     {% else %}
      <li class="nav-item dropdown">

      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <img style="width: 25px;" src="{{ user|gravatar:60 }}"/><span>  {{user.username}}</span><b class="caret"></b></a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a href="{% url 'logout' %}?next={% url 'home:main' %}">Logout</a>
            <a href="{% url 'membership:member_detail' user.id %}">View Profile</a>
       </div>
      </li>
       {% endif %}
    </ul>
</div>
</nav> -->


{% endblock %}