amplifiers/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name = 'amplifiers'

urlpatterns = [
    path('', views.AmplifierListView.as_view(), name='all'),
    path('list/<int:pk>', views.AmplifierDetailView.as_view(), name='amplifier_detail'),
    path('amplifier/create', views.AmplifierCreateView.as_view(success_url=reverse_lazy('amplifier:all')), name='amplifier_create'),
    path('amplifier_picture/<int:pk>', views.stream_file, name='amplifier_picture'),

]

audiolibrary/urls.py
import os
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.views.static import serve
from django.views.generic import TemplateView


urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),  # Keep
    re_path(r'^oauth/', include('social_django.urls', namespace='social')),

    # application
    path('speakers/', include('speakers.urls')),
    path('amplifiers/', include('amplifiers.urls')),
    path('genre/', include('genre.urls')),
    path('library/', include('library.urls')),
    path('forum', include('forum.urls')),
    path('membership', include('membership.urls')),

]

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    re_path(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

home/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

app_name = 'home'

urlpatterns = [
    path('', TemplateView.as_view(template_name='home/main.html'), name='main'),
    path('register', views.register_request, name="register"),
    path('user', views.userpage, name="userprofile"),
]

amplifiers/models.py
from django.db import models


# Create your models here.

class Amplifier(models.Model):
    amplifier_type_choice = (
        (0, 'Pre-Amp'),
        (1, 'Power-Amp')
    )
    model = models.CharField('Amplifier Model', max_length=128, unique=True)
    amplifier_type = models.SmallIntegerField('Amplifier Type', choices=amplifier_type_choice, default=0)
    manufacturer = models.ForeignKey('Manufacturer', on_delete=models.CASCADE, verbose_name="Amplifier Manufacturer")
    description = models.TextField()
    specification = models.TextField()
    picture = models.BinaryField(null=True, blank=True, editable=True)
    content_type = models.CharField(max_length=256, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.model

    class Meta:
        verbose_name = "Amplifier"
        verbose_name_plural = "Amplifier"


class Manufacturer(models.Model):
    name = models.CharField('Amplifier Manufacturer Name', max_length=128)
    text = models.TextField('Manufacturer Description')
    existed = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Manufacturer"
        verbose_name_plural = "Manufacturer"

amplifiers/forms.py
from django import forms
from amplifiers.models import Amplifier
from django.core.files.uploadedfile import InMemoryUploadedFile
from humanize import naturalsize


class AmplifierForm(forms.ModelForm):
    max_upload_limit = 2 * 1024 * 1024
    max_upload_limit_text = naturalsize(max_upload_limit)
    picture = forms.FileField(required=False, label='File to Upload <=' + max_upload_limit_text)
    upload_field_name = 'picture'

    class Meta:
        model = Amplifier
        fields = ['model', 'amplifier_type', 'manufacturer', 'picture']

        # Validate the size of the picture

    def clean(self):
        cleaned_data = super().clean()
        pic = cleaned_data.get('picture')
        if pic is None:
            return
        if len(pic) > self.max_upload_limit:
            self.add_error('picture', "File must be < " + self.max_upload_limit_text + " bytes")

        # Convert uploaded File object to a picture

    def save(self, commit=True):
        instance = super(AmplifierForm, self).save(commit=False)

        # We only need to adjust picture if it is a freshly uploaded file
        f = instance.picture  # Make a copy
        if isinstance(f, InMemoryUploadedFile):  # Extract data from the form to the model
            bytearr = f.read()
            instance.content_type = f.content_type
            instance.picture = bytearr  # Overwrite with the actual image data

        if commit:
            instance.save()

        return instance

amplifiers/views.py
from django.views import View
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.http import HttpResponse
from amplifiers.models import Amplifier
from amplifiers.forms import AmplifierForm
from home.owner import OwnerListView, OwnerDetailView


# Create your views here.

class AmplifierListView(OwnerListView):
    model = Amplifier
    template_name = "amplifier/index.html"


class AmplifierDetailView(OwnerDetailView):
    model = Amplifier
    template_name = "amplifier/detail.html"


class AmplifierCreateView(View):
    template_name = "amplifier/forms.html"
    success_url = reverse_lazy('amplifiers:all')

    def get(self, request, pk=None):
        form = AmplifierForm()
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        form = AmplifierForm(request.POST, request.FILES or None)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        amplifier = form.save(commit=False)
        amplifier.save()
        return redirect(self.success_url)

def stream_file(request, pk):
    pic = get_object_or_404(Amplifier, id=pk)
    response = HttpResponse()
    response['Content-Type'] = pic.content_type
    response['Content-Length'] = len(pic.picture)
    response.write(pic.picture)
    return response

amplifiers/templates/amplifier/detail.html
{% extends 'base_menu.html' %}
{% block title %}{{ settings.APP_NAME }}{% endblock %}
{% load humanize %} <!-- 加載標籤和過濾器 -->
{% block head %}
<style>
.overlay{
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    z-index: 10;
    display: none;
    background-color: rgba(0,0,0,0.5);
}
</style>
{% endblock %}

{% block content %}

{% if amplifier.content_type %}
    <div id="overlay" class="overlay" style="text-align: center;" onclick="document.getElementById('overlay').style.display = 'none';">
    <img style="width: 90%; margin-top: 50px; border: 3px solid black;" src="{% url 'amplifiers:amplifier_picture' amplifier.id %}">
    </div>
{% endif %}

<span style="float: right;">
({{ amplifier.updated_at|naturaltime }})
</span>

<h1>{{ amplifier.model }}</h1>
    <h2>{{ amplifier.manufacturer }}</h2>
    {% if amplifier.content_type %}
    <img style="float:right; max-width:50%;" src="{% url 'amplifiers:amplifier_picture' amplifier.id %}" onclick="document.getElementById('overlay').style.display = 'block';">
    {% endif %}
    <p>
    {{ amplifier.text }}
    </p>

{% endblock %}

amplifiers/templates/amplifier/forms.html
{% extends 'base_menu.html' %}
{% block title %}{{ settings.APP_NAME }}{% endblock %}

{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block content %}
<p>
  <form action="" method="post" id="upload_form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit">
    <input type="submit" value="Cancel" onclick="window.location.href='{% url 'amplifiers:all' %}';return false;">
  </form>
</p>
<!-- https://stackoverflow.com/questions/2472422/django-file-upload-size-limit -->
<script>
$("#upload_form").submit(function() {
  console.log('Checking file size');
  if (window.File && window.FileReader && window.FileList && window.Blob) {
      var file = $('#id_{{ form.upload_field_name }}')[0].files[0];
      if (file && file.size > {{ form.max_upload_limit }} ) {
          alert("File " + file.name + " of type " + file.type + " must be < {{ form.max_upload_limit_text }}");
      return false;
    }
  }
});
</script>
{% endblock %}

amplifiers/templates/amplifier/index.html
{% extends 'base_menu.html' %}
{% block title %}{{ settings.APP_NAME }}{% endblock %}
{% block content %}
<h1>Amplifier</h1>
    <p>
    {% if amplifier_list %}
<ul>
{% for amplifier in amplifier_list %}
    <li>
    <a href="{% url 'amplifiers:amplifier_detail' amplifier.id%}">{{ amplifier.model }}</a>
    </li>
{% endfor %}
</ul>
    {% else %}
        <p> There are no amplifiers in the database.</p>
    {% endif %}
    </p>

    <p>
    <a href="{% url 'amplifiers:amplifier_create' %}">Create a amplifier</a>|
{% if user.is_authenticated %}
<a href="{% url 'logout' %}?next={% url 'amplifiers:all' %}">Logout</a>
{% else %}
<a href="{% url 'login' %}?next={% url 'amplifiers:all' %}">Login</a>
{% endif %}


    </p>

{% endblock %}